name: autotag
on:
  push:
    branches:
      - main
      - fix-tags-multiline-commit

jobs:
  tag:
    permissions:
      # permission required to create tag
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/tag
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
