name: autotag
on: [push]

jobs:
  tag:
    permissions:
      # permission required to create tag
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/tag
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: ${{ github.ref_name == 'main' }}
